name: PyPI package tests

on:
  #####################################
  push:
    branches: [ master, main, develop ]
  #####################################
  # Run daily, at 00:00.
  schedule:
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent workflow, skipping runs queued between the run
# in-progress and latest queued. And cancel in-progress runs.
concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Set the environment variables to be used in all jobs defined in this workflow
env:
  CI_BRANCH: ${{ github.head_ref || github.ref_name }}
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  # Job 1: Test installation from PyPI on multiple OS
  pypi-package-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up pixi
        uses: ./.github/actions/setup-pixi
        with:
          environments: ''
          activate-environment: ''
          run-install: false
          frozen: false

      - name: Init pixi project
        run: pixi init easydiffraction

      - name: Add Python 3.13 from Conda
        working-directory: easydiffraction
        run: pixi add "python=3.13"

      - name: Add other Conda dependencies
        working-directory: easydiffraction
        run: pixi add gsl

      - name: Add easydiffraction from PyPI
        working-directory: easydiffraction
        run: pixi add --pypi "easydiffraction[dev]"

      - name: Add Pixi task as a shortcut
        working-directory: easydiffraction
        run: pixi task add easydiffraction "python -m easydiffraction"

      - name: Run unit tests to verify the installation
        working-directory: easydiffraction
        run: pixi run python -m pytest ../tests/unit/ --color=yes -v

      - name: Run integration tests to verify the installation
        working-directory: easydiffraction
        run: pixi run python -m pytest ../tests/integration/ --color=yes -n auto

      # Github token to avoid hitting the unauthenticated API rate limit
      - name: List and fetch the easydiffraction tutorials
        working-directory: easydiffraction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pixi run easydiffraction --version
          pixi run easydiffraction list-tutorials
          pixi run easydiffraction download-all-tutorials

      - name: Test tutorials as notebooks
        working-directory: easydiffraction
        run: pixi run notebook-tests

  # Job 2: Trigger dashboard build
  #dashboard-build-trigger:
  #  needs: pypi-package-tests

  #  runs-on: ubuntu-latest

  #  steps:
  #    - name: Check-out repository
  #      uses: actions/checkout@v5

  #    - name: Trigger dashboard build
  #      uses: actions/github-script@v7
  #      with:
  #        github-token: ${{ secrets.GITHUB_TOKEN }}
  #        script: |
  #          await github.rest.actions.createWorkflowDispatch({
  #            owner: context.repo.owner,
  #            repo: context.repo.repo,
  #            workflow_id: "dashboard.yaml",
  #            ref: "${{ env.CI_BRANCH }}"
  #          });
